name: web-test
replicaCount: 2

image:
  repository: huytruongnguyen/web-test
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 31577

ingress:
  enabled: false
